"""Add codigo_tidy column to clients

Revision ID: 11c1b36ffe98
Revises: 791bb8cb3706
Create Date: 2025-02-08 16:04:11.073028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c1b36ffe98'
down_revision: Union[str, None] = '791bb8cb3706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('codigo_tidy', sa.String(), nullable=True))
    op.alter_column('clients', 'empresas_trabalhadas',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'empresas_trabalhadas',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('clients', 'codigo_tidy')
    # ### end Alembic commands ###
