"""Adiciona latitude e longitude

Revision ID: 791bb8cb3706
Revises: 
Create Date: 2025-02-07 09:47:27.351080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791bb8cb3706'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'longitude')
    op.drop_column('clients', 'latitude')
    # ### end Alembic commands ###
